In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://assignment_user:assignment_password@localhost:5432/assignment_database')

# 1. Find the most frequent members

In [2]:

frequent_members_query = """
select member_id, count(visit_date) as num_of_visits
from visits 
group by member_id
order by count(visit_date) desc
limit 10
"""
df_frequent = pd.read_sql(frequent_members_query, engine)
display(df_frequent)

   member_id  num_of_visits
0       4338             11
1       3737             11
2       1379             11
3       2193             11
4       2271             11
5       3180             10
6       4864             10
7       2625             10
8       3082             10
9       3248             10

# 2. Find the most bought items

In [3]:
most_bought_items_query = """
select item_name, count(visit_id) as times_bought
from sales
group by item_name
order by count(visit_id) desc
limit 10
"""
df_bought_items = pd.read_sql(most_bought_items_query, engine)
display(df_bought_items)

          item_name  times_bought
0        whole milk          2502
1  other vegetables          1898
2        rolls/buns          1716
3              soda          1514
4            yogurt          1334
5   root vegetables          1071
6    tropical fruit          1032
7     bottled water           933
8           sausage           924
9      citrus fruit           812

# 3. Find the biggest cart in the database (= the largest number of items bought together)

In [4]:
biggest_cart_query = """
select s.visit_id, v.visit_date, v.member_id, count(s.item_name) as num_of_items
from sales as s
left join visits as v on s.visit_id = v.id
group by s.visit_id, v.visit_date, v.member_id
order by count(s.item_name) desc
limit 10
"""
df_biggest_cart = pd.read_sql(biggest_cart_query, engine)
display(df_biggest_cart)

   visit_id  visit_date  member_id  num_of_items
0      2178  2015-07-12       1780            11
1      2120  2015-03-11       3050             9
2      2134  2015-11-29       3051             9
3      2137  2015-06-25       2142             9
4      2141  2015-03-09       2086             9
5      2130  2015-11-09       4486             9
6      2112  2015-07-29       2792             9
7      2126  2015-04-29       1407             9
8      2133  2015-04-15       3752             9
9      2132  2015-07-01       2186             9

# 4. Find all the products under a category (e.g. `Meat-Seafood`)

In [ ]:
query = """
select item_name
from items
where cat_level_1 = 'Meat-Seafood'
"""
df_query = pd.read_sql(query, engine)
display(df_query)

         item_name
0             beef
1          chicken
2             fish
3      frankfurter
4   frozen chicken
5      frozen fish
6              ham
7   hamburger meat
8       liver loaf
9             meat
10            pork
11         sausage
12          turkey

# 5. Find all the first-level children of a category (e.g. `Dairy-Eggs-Cheese`)

In [10]:
query = """
select cat_level_2, cat_level_3
from items
where cat_level_1 = 'Dairy-Eggs-Cheese'
"""
df_query = pd.read_sql(query, engine)
display(df_query)

          cat_level_2        cat_level_3
0   Butter-Sour-Cream             Butter
1          Milk-Cream         Buttermilk
2          Milk-Cream     Whipping-Cream
3              Cheese       Cream-Cheese
4              Cheese     Cottage-Cheese
5              Cheese     Cottage-Cheese
6                Eggs               None
7              Cheese    Sandwich-Cheese
8   Butter-Sour-Cream  Margarine-Spreads
9              Cheese  Loaf-Block-Cheese
10             Cheese    Sandwich-Cheese
11             Cheese       Cream-Cheese
12             Cheese       Cream-Cheese
13         Milk-Cream               Milk
14  Butter-Sour-Cream         Sour-Cream
15         Milk-Cream               Milk
16     Yogurt-Pudding             Yogurt